# automatically generated by the FlatBuffers compiler, do not modify

# namespace: hyperionnet

import flatbuffers

class Reply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsReply(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Reply()
        x.Init(buf, n + offset)
        return x

    # Reply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Reply
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return bytes()

    # Reply
    def Video(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return -1

def ReplyStart(builder): builder.StartObject(2)
def ReplyAddError(builder, error): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)
def ReplyAddVideo(builder, video): builder.PrependInt32Slot(1, video, -1)
def ReplyEnd(builder): return builder.EndObject()
