# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

import flatbuffers

class ClearRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsClearRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClearRequest()
        x.Init(buf, n + offset)
        return x

    # ClearRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClearRequest
    def Priority(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ClearRequestStart(builder): builder.StartObject(1)
def ClearRequestAddPriority(builder, priority): builder.PrependInt32Slot(0, priority, 0)
def ClearRequestEnd(builder): return builder.EndObject()
