# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

import flatbuffers

class ColorRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsColorRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ColorRequest()
        x.Init(buf, n + offset)
        return x

    # ColorRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ColorRequest
    def Priority(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ColorRequest
    def RgbColor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ColorRequest
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ColorRequestStart(builder): builder.StartObject(3)
def ColorRequestAddPriority(builder, priority): builder.PrependInt32Slot(0, priority, 0)
def ColorRequestAddRgbColor(builder, RgbColor): builder.PrependInt32Slot(1, RgbColor, 0)
def ColorRequestAddDuration(builder, duration): builder.PrependInt32Slot(2, duration, 0)
def ColorRequestEnd(builder): return builder.EndObject()
